import type { GameDefinition } from "./contracts";
export const games: GameDefinition[] = [
  {
    id: "tetris",
    path: "/tetris",
    title: "home.tetris.title",
    description: "home.tetris.description",
    tag: "10 × 20",
    load: () => import("./tetris/Game.vue"),
  },
  {
    id: "sudoku",
    path: "/sudoku",
    title: "home.sudoku.title",
    description: "home.sudoku.description",
    tag: "9 × 9",
    load: () => import("./sudoku/Game.vue"),
  },
  {
    id: "twenty48",
    path: "/twenty48",
    title: "home.twenty48.title",
    description: "home.twenty48.description",
    tag: "4 × 4",
    load: () => import("./twothousandfortyeight/Game.vue"),
  },
  {
    id: "snake",
    path: "/snake",
    title: "home.snake.title",
    description: "home.snake.description",
    tag: "20 × 20",
    load: () => import("./snake/Game.vue"),
  },
  {
    id: "gomoku",
    path: "/gomoku",
    title: "home.gomoku.title",
    description: "home.gomoku.description",
    tag: "15 × 15",
    load: () => import("./gomoku/Game.vue"),
  },
  {
    id: "npuzzle",
    path: "/npuzzle",
    title: "home.npuzzle.title",
    description: "home.npuzzle.description",
    tag: "3 × 3 / 4 × 4",
    load: () => import("./npuzzle/Game.vue"),
  },
  {
    id: "bubble",
    path: "/bubble",
    title: "home.bubble.title",
    description: "home.bubble.description",
    tag: "6 COLORS",
    load: () => import("./bubble/Game.vue"),
  },
];
